#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 400
#define COMBO_VARIABLE_LEN
#define COMBO_TERM 90
// reduce size of resulting image
#define LAYER_STATE_8BIT
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_MUSIC_MODE
