VPATH += keyboards/gboards/
COMBO_ENABLE=yes
SRC += flow.c
REPEAT_KEY_ENABLE=yes
STENO_ENABLE=yes
STENO_PROTOCOL=geminipr
EXTRAKEY_ENABLE=yes
# reduce size of resulting image
MAGIC_ENABLE=no
LTO_ENABLE=yes
MOUSEKEY_ENABLE=no
CONSOLE_ENABLE=no
COMMAND_ENABLE=no
SPACE_CADET_ENABLE=no
GRAVE_ESC_ENABLE=no
AVR_USE_MINIMAL_PRINTF=yes
MUSIC_ENABLE=no
